import type { NextPage } from 'next';
import Head from 'next/head';


import { HeadNext } from "../components/HeadNext";
import { Main } from "../components/Main";
import { AboutMe } from "../components/AboutMe";
import { Projects } from "../components/Projects";
import { Resume } from "../components/Resume";
import { Menu } from "../components/Menu";
import { Header } from '../components/Header';

export type Info = {
  tituloOfPage: string;
  nome: string;
  subtitulo: string;
  biografia: string;
};

export const info: Info = {
  tituloOfPage: 'Herlmanoel',
  nome: 'Herlmanoel Fernandes Barbosa',
  subtitulo: 'Desenvolvedor Back-end Java, Spring Boot, Oracle PL/SQL | Desenvolvedor Front-end React',
  biografia: 'Sou Desenvolvedor de Software, de Natal, Rio Grande do Norte. Programando desde 2016, ano em que ingressei no curso Técnico Integrado ao ensino médio em Informática no IFRN e, desde lá, nunca parei. Me vi fascinado por resolver problemas utilizando programação. Neste meio tempo, adquiri experiência em implantação e manutenção de sistemas, utilizando metodologias ágeis para gestão de projetos.',
};

const Home: NextPage = () => {
  return (
    <div className="home-content-center">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Menu />
      <Main>
        <Header info={info} />
        <AboutMe info={info} />
        <Resume />
        <Projects />
      </Main>
    </div>
  )
}

export default Home;
