import Head from "next/head";

export const HeadNext = ({ tituloOfPage }) => {
  return (
    <Head>
      <title>{tituloOfPage}</title>
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" href="/favicon.ico" />
    </Head>
  );
};
